#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/LisuTzimu-Regular.ufo
psfnormalize -p checkfix=fix source/LisuTzimu-Bold.ufo
psfnormalize -p checkfix=fix source/LisuTzimu-Italic.ufo
psfnormalize -p checkfix=fix source/LisuTzimu-BoldItalic.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/LisuTzimuRoman.designspace source/LisuTzimuItalic.designspace
