#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo source/LisuTzimuRoman.glyphs source -l source/logs/glyphs2ufoR.log
psfglyphs2ufo source/LisuTzimuItalic.glyphs source -l source/logs/glyphs2ufoI.log

./preflight