#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/LisuTzimu-Regular.ufo -l source/logs/normR.log
psfnormalize -p checkfix=fix source/LisuTzimu-Bold.ufo  -l source/logs/normB.log
psfnormalize -p checkfix=fix source/LisuTzimu-Italic.ufo -l source/logs/normI.log
psfnormalize -p checkfix=fix source/LisuTzimu-BoldItalic.ufo -l source/logs/normBI.log

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/LisuTzimuRoman.designspace source/LisuTzimuItalic.designspace -l source/logs/sync.log
